spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vcode-sso?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
#    username: ${MYSQL_USER}@localhost
#    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
